swagger: '2.0'
info:
  title: USER DEVICE ENFORCEMENT API
  description: User Device Enformcement API
  version: 0.0.1
schemes:
  - https
  - http
host: localhost:8080
produces:
  - application/json
paths:
  /getPrivacySettings:
    get:
      summary: Get Privacy Settings
      description: |
        The UDE endpoint returns the current privacy settings for all social
        networks. It is called by Watchdog when it requests to get current
        settings
      parameters:
        - name: user_id
          in: query
          description: Unique identifier representing a specific user or service
          type: string
          required: true
          format: uuid
        - name: osp_list
          in: body
          description: OSP_list
          schema: 
            $ref: '#/definitions/OSP'
      tags: 
        - PrivacySettings
        - GET
      responses:
        '200':
          description: An array of privacy settings
          schema:
            type: array
            items:
              $ref: '#/definitions/PrivacySettings'
        default:
            description: Unexpected error
            schema:
              $ref: '#/definitions/Error'
  /applyPrivacySettings:
    post:
      summary: Apply Privacy Settings
      description: Called by OSE when it wants to update user’s settings
      parameters:
        - name: user_id
          in: query
          description: Unique identifier representing a specific user or service
          type: string
          required: true
          format: uuid 
        - name: osp_id  
          in: query
          description: OSP unique identifier
          type: string
          required: true
      tags: 
        - PrivacySettings  
        - POST
      responses:
        '200':
          description: Privacy Setting were successfully applied
          schema:
             $ref: '#/definitions/Status'
  /getOffers:
    get:
      summary: Get website offers
      description: Extension sends request to PfB service to get a list of offers for the website when signup page is detected
      parameters: 
        - name: user_id
          in: query
          description: Unique identifier representing a specific user from the UDE service
          type: string
          required: true
          format: uuid
        - name: website
          in: query
          description: Website address 
          type: string
          required: true
      tags:
        - PrivacyForBenefits
        - GET
      responses:
        '200':
          description: An array containing all available offers for the requested website
          schema: 
            type: array
            items:  
              $ref : '#/definitions/Offer'
  /requestOffer:
    post:
      description : Triggered by the extension to PfB service to indicate that the user has chosen to accept the offer (i.e. initiated login with Social Network button)
      tags:
        - PrivacyForBenefits
        - POST
      parameters:
        - name: user_id
          in: query
          description: Unique identifier representing a specific user from the UDE service
          type: string
          required: true
          format: uuid
        - name: offer_id
          in: query
          description: Unique identifier for an offer
          type: string
          required: true
          format: uuid
      responses:
        200:
          description: Successfull request
          schema:
            $ref: '#/definitions/Status'
        500:
          description: Failed request
          schema:
            $ref: '#/definitions/Status'
  
  /getPendingDeals:
    get:
      description: Extension requests from PfB service the list of all pending deal requests for a user
      tags:
        - PrivacyForBenefits
        - GET
      parameters:
        - name: user_id
          in: query
          description: Unique identifier representing a specific user from the UDE service
          type: string
          required: true
          format: uuid
      responses:
        200:  
          description: A list of offers
          schema:
            type: array
            items:
              $ref: '#/definitions/Offer'
  
  /getOfferStatus:
    get:
      description: Get offer status
      tags:
        - PrivacyForBenefits
        - GET
      parameters: 
        - name: offer_id
          in: query
          description: Unique identifier for an offer
          type: string
          required: true
          format: uuid
      responses: 
        200:
          description: Get offer status (active | inactive)
          schema:
            $ref: '#/definitions/Status'		  

definitions:
  PrivacySettings:
    type: object
    properties:
      id:
        type: string
        description: PrivacySetting Unique Identifier
      description:
        type: string
        description : Description of the setting
      name:
        type: string
        description: Short name of the setting
      setting_target:
        type: string
        description: Targeted setting key
      setting_value:
        type: string
        description: Targeted setting value   
  OSP:
    type: object
    properties: 
      id:
        type: string
        description: OSP Unique Identifier
      description:
        type: string
        description : Description of the OSP
      name:
        type: string
        description: Short name of the OSP
  Offer:
    type: object
    properties:
      offer_id:
        type: integer
        format: int32
        description: Offer unique identifier
      title:
        type: string
        description: The offer title
      description  :
        type: string
        description: The offer description

  Status:
    type: object
    properties:
      status:
        type: string
        description: Request status success or error
      message:
        type: string
        description: Status message 
  Error:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      fields:
        type: string
